//
//  Workspace.swift
//  ConqreteNamespace
//
//  Created by stilltimm on 13/08/2022.
//  Copyright © 2022 com.conqrete. All rights reserved.
//

import ProjectDescription

let workspace = Workspace(
    name: "ConqreteNamespace",
    projects: ["."],
    generationOptions: .options(
        enableAutomaticXcodeSchemes: false,
        autogeneratedWorkspaceSchemes: .disabled,
        renderMarkdownReadme: true
    )
)