default_platform(:ios)

platform :ios do

  desc "Build & Test"
  lane :test do
    run_tests(
      workspace: "ConqreteNamespace.xcworkspace",
      scheme: "ConqreteNamespace",
      code_coverage: true
    )
  end

end
