default_platform(:ios)

platform :ios do

  desc "Run tests"
  lane :tests do
    run_tests(
      workspace: "ConqreteNamespace.xcworkspace",
      scheme: "ConqreteNamespace",
      code_coverage: true
    )
  end

end
